import fs from "fs";
import path from "path";

const ICON_DIR = path.join(__dirname, "../public/icons");
const OUTPUT_DIR = path.join(__dirname, "../dist");
const OUTPUT_FILE = path.join(OUTPUT_DIR, "infotravel-icons.css");
const PREFIX = "icone";

if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

const icons = fs.readdirSync(ICON_DIR).filter((file) => file.endsWith(".svg"));

let cssContent = `
/* Generated by infotravel-icons */
[class^="${PREFIX}-"], [class*=" ${PREFIX}-"] {
  display: inline-block;
  width: 1em;
  height: 1em;
  background-repeat: no-repeat;
  background-position: center;
  background-size: contain;
  vertical-align: middle;
}
`;

icons.forEach((icon) => {
  const iconName = path.basename(icon, ".svg");
  // Handle spaces and other chars in filenames safely if needed,
  // but for now assuming standard 'kebab-case' or similar.
  // The user requirement specific example "icon-flag-brazil" suggests we map filename "flag-brazil.svg" to class ".icon-flag-brazil".

  // Robust slugification:
  // 1. Normalize to NFD to separate accents
  // 2. Remove diacritical marks
  // 3. Replace non-alphanumeric chars (except hyphens) with hyphens
  // 4. Collapse multiple hyphens
  // 5. Trim hyphens
  const slug = iconName
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  const className = `${PREFIX}-${slug}`;
  const filePath = path.join(ICON_DIR, icon);
  const svgContent = fs.readFileSync(filePath, "utf-8");

  // Basic optimization: remove newlines and excessive whitespace could be added here
  // For now, encoding directly.
  // Determine type: Flag, Mixed-Color (needs inversion), or Standard Monochrome
  const isFlag = slug.startsWith("flag-");

  // Check for presence of white/light colors that might be intended as holes
  // (Simplified check: looks for 'white' or '#fff' AND other colors)
  // We ignore 'none'
  const hasWhite = /(["':\s])(white|#fff|#ffffff)(["';\s])/i.test(svgContent);
  const colorMatches = svgContent.match(/#([0-9a-fA-F]{3,6})/gi) || [];
  const distinctColors = new Set(colorMatches.map((c) => c.toLowerCase()));
  // remove white/none like colors if any (e.g. #fff, #ffffff)
  distinctColors.delete("#fff");
  distinctColors.delete("#ffffff");

  const hasOtherColors = distinctColors.size > 0;
  const isMixedColor = !isFlag && hasWhite && hasOtherColors;

  let finalSvg = svgContent;
  let useLuminance = false;

  if (isMixedColor) {
    // Invert colors creates a "Negative" for the mask
    // White (holes) -> Black
    // Other Colors (body) -> White
    useLuminance = true;

    // 1. Replace white/FFF with a placeholder to avoid collision
    finalSvg = finalSvg.replace(
      /(["':\s])(white|#fff|#ffffff)(["';\s])/gi,
      "$1__HOLE__$3",
    );

    // 2. Replace all other hex colors with White
    finalSvg = finalSvg.replace(/#([0-9a-fA-F]{3,6})/gi, "#ffffff");

    // 3. Replace placeholder with Black
    finalSvg = finalSvg.replace(/__HOLE__/g, "#000000");
  }

  const base64 = Buffer.from(finalSvg).toString("base64");
  const dataUri = `data:image/svg+xml;base64,${base64}`;

  if (isFlag) {
    cssContent += `
.${className} {
  background-image: url('${dataUri}');
}
`;
  } else {
    // Monochrome icon: use mask-image
    const maskMode = useLuminance
      ? "mask-mode: luminance; -webkit-mask-mode: luminance;"
      : "";

    cssContent += `
.${className} {
  -webkit-mask-image: url('${dataUri}');
  mask-image: url('${dataUri}');
  -webkit-mask-repeat: no-repeat;
  mask-repeat: no-repeat;
  -webkit-mask-position: center;
  mask-position: center;
  -webkit-mask-size: contain;
  mask-size: contain;
  background-color: currentColor;
  ${maskMode}
}
`;
  }
});

fs.writeFileSync(OUTPUT_FILE, cssContent);
console.log(`Generated ${OUTPUT_FILE} with ${icons.length} icons.`);

const HTML_FILE = path.join(OUTPUT_DIR, "infotravel-icons.html");
let htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Infotravel Icons</title>
    <link rel="stylesheet" href="infotravel-icons.css">
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            padding: 40px;
            background: #f5f5f7;
            margin: 0;
        }
        h1 { text-align: center; margin-bottom: 40px; color: #333; }
        p { text-align: center; margin-bottom: 30px; color: #666; }

        .icon-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
            gap: 24px;
            max-width: 1200px;
            margin: 0 auto;
        }

        .icon-item {
            background-color: #fff;
            border-radius: 12px;
            padding: 24px;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            box-shadow: 0 2px 8px rgba(0,0,0,0.05);
            transition: transform 0.2s, box-shadow 0.2s;
            height: 160px;
        }

        .icon-item:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
        }

        /* Dark mode card */
        .icon-item.dark {
            background-color: #2d2d2d;
            color: #fff;
            border: 1px solid #444;
        }

        [class^="${PREFIX}-"], [class*=" ${PREFIX}-"] {
            font-size: 32px;
            margin-bottom: 16px;
            display: inline-block;
            width: 1em;
            height: 1em;
        }

        code {
            display: block;
            font-size: 11px;
            font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;
            color: #86868b;
            word-break: break-word;
            background: #f5f5f7;
            padding: 4px 8px;
            border-radius: 4px;
            margin-top: auto;
            max-width: 100%;
        }

        .icon-item.dark code {
            background: #444;
            color: #ccc;
        }

        .icon-item.big i {
            font-size: 48px;
        }
    </style>
</head>
<body>
    <h1>Infotravel Icons Preview</h1>
    <p>Icons are displayed on both light and dark backgrounds to ensure visibility.</p>
    <div class="icon-grid">
`;

icons.forEach((icon) => {
  // Re-calculate slug to match the loop above (ideal refactor would be to map first)
  const slug = path
    .basename(icon, ".svg")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  // Generate two previews per icon: one light, one dark
  htmlContent += `
        <div class="icon-item">
            <i class="${PREFIX}-${slug}"></i>
            <code>${PREFIX}-${slug}</code>
        </div>
        <div class="icon-item dark">
            <i class="${PREFIX}-${slug}"></i>
            <code>${PREFIX}-${slug}</code>
        </div>
        <div class="icon-item">
            <i class="${PREFIX}-${slug}" style="color: #e63946;"></i>
            <code style="color: #e63946;">color: #e63946</code>
        </div>
        <div class="icon-item big">
            <i class="${PREFIX}-${slug}"></i>
            <code>font-size: 48px</code>
        </div>`;
});

htmlContent += `
    </div>
</body>
</html>
`;

fs.writeFileSync(HTML_FILE, htmlContent);
console.log(`Generated ${HTML_FILE}`);
